const frogNames = [

]

const rattributesArray = [
    "evil",
    "moist eyed",
    "speaks mouse",
    "speaks elvish",
    "rabid",
    "shy",
    "passive-aggressive",
    "weak willed",
    "chemical dependency",
    "gay",
    "bi-curious",
    "flamboyant",
    "dark",
    "sanguine",
    "pretty",
    "cute",
    "night owl",
    "nudist",
    "greedy",
    "jealous",
    "pyromaniac",
    "cannibal",
    "nimble",
    "wimp",
    "annoying squeak",
    "very neurotic",
    "restless",
    "murderer",
    "loves mice",
    "cat killer",
    "cat lover",
    "a rat amongst rats",
    "plague spreader",
    "cocaine addiction",
    "button presser",
    "sexual deviant",
    "forgetful",
    "lazy",
    "smart",
    "snappy dresser",
    "talks too much",
    "sneaky",
    "ambivalent towards mice",
    "crazy",
    "loves to cook",
    "overweight",
    "classy",
    "class act",
    "prefers the company of mice",
    "rat about town",
    "hates mice",
    "people pleaser",
    "brave",
    "descended from royalty",
    "beautiful",
    "sarcastic",
    "mistrustful of humans",
    "narcissistic",
    "holier than thou",
    "friend of cats",
  ];