const frogNames = [
  "Aaron",
  "Ben"
]

const traitsArray = [
    "evil",
    "moist eyed",
    "speaks mouse",
    "speaks toad",
    "rabid",
    "shy",
    "passive-aggressive",
    "weak willed",
    "chemical dependency",
    "gay",
    "bi-curious",
    "flamboyant",
    "dark",
    "sanguine",
    "pretty",
    "cute",
    "night owl",
    "nudist",
    "greedy",
    "jealous",
    "pyromaniac",
    "cannibal",
    "nimble",
    "wimp",
    "annoying croak",
    "very neurotic",
    "restless",
    "murderer",
    "loves mice",
    "toad killer",
    "toad lover",
    "a frog amongst frogs",
    "plague spreader",
    "cocaine addiction",
    "button presser",
    "sexual deviant",
    "forgetful",
    "lazy",
    "smart",
    "snappy dresser",
    "talks too much",
    "sneaky",
    "ambivalent towards mice",
    "crazy",
    "loves to cook",
    "overweight",
    "classy",
    "class act",
    "prefers the company of newts",
    "frog about town",
    "hates toads",
    "people pleaser",
    "brave",
    "descended from royalty",
    "beautiful",
    "sarcastic",
    "mistrustful of humans",
    "narcissistic",
    "holier than thou",
    "friend of toads",
  ];